version: '3.8'

services:
  # db service
  db:
    build:
      context: src/db
      dockerfile: Dockerfile
    image: copilot-postgresql-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - ./src/db/data:/var/lib/postgresql/data
    networks:
      - copilot-network
    restart: "no"

  # support tool for db
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./src/pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - db
    networks:
      - copilot-network
    restart: "no"

  copilot:
    build:
      context: src/copilot
      dockerfile: Dockerfile
    image: copilot
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./src/copilot/app:/app
    networks:
      - copilot-network
    depends_on:
      - db
    restart: "no"

  # frontend
  zas-copilot:
    build:
      context: https://github.com/CdC-SI/copilot-frontend.git#main
    image: zas-copilot:latest
    ports:
      - "4200:4200"
    networks:
      - copilot-network
    depends_on:
      - copilot
    restart: "no"

networks:
  copilot-network:
    driver: bridge