version: '3.8'

services:
  # db service
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: copilot-postgresql-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - copilot-network
    restart: "no"

  # support tool for db
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - db
    networks:
      - copilot-network
    restart: "no"

  autocomplete:
    build:
      context: .
      dockerfile: ./autocomplete/Dockerfile
    image: copilot-autocomplete
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
    volumes:
      - .:/app
    networks:
      - copilot-network
    depends_on:
      - db
    restart: "no"

  # data indexing
  indexing:
    build:
      context: .
      dockerfile: ./indexing/Dockerfile
    image: copilot-indexing
    ports:
      - "8011:8011"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
    volumes:
      - .:/app
    networks:
      - copilot-network
    depends_on:
      - db
    restart: "no"

  # frontend
  chatgpt-minimal:
    build:
      context: https://github.com/CdC-SI/chatgpt-minimal.git#main
    image: chatgpt-minimal
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REACT_APP_QUERY_AUTOCOMPLETE_API_URL=${REACT_APP_QUERY_AUTOCOMPLETE_API_URL}
    networks:
      - copilot-network
    depends_on:
      - autocomplete
    restart: "no"

  # RAG
  rag:
    build:
      context: .
      dockerfile: ./rag/Dockerfile
    image: copilot-rag
    ports:
      - "8010:8010"
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
    volumes:
      - .:/app
    networks:
      - copilot-network
    depends_on:
      - db
    restart: "no"

networks:
  copilot-network:
    driver: bridge