version: '3.8'

services:

  # db service
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: copilot-postgresql-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - copilot-network

  # support tool for db
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - db
    networks:
      - copilot-network

  # fassade
  fastapi:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: copilot-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - ./api/app:/app
    networks:
      - copilot-network
    depends_on:
      - db

  # frontend
  chatgpt-minimal:
    build: ../chatgpt-minimal
    image: chatgpt-minimal
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REACT_APP_QUERY_AUTOCOMPLETE_API_URL=${REACT_APP_QUERY_AUTOCOMPLETE_API_URL}
    networks:
      - copilot-network
    depends_on:
      - fastapi

  # LLM stuff
  chatbot:
    build:
      context: ./chatbot
      dockerfile: Dockerfile
    image: copilot-chatbot
    ports:
      - "8009:8009"
    volumes:
      - ./chatbot/app:/app
    networks:
      - copilot-network

networks:
  copilot-network:
    driver: bridge