# Check https://cdc-si.github.io/eak-copilot/ to access config.yaml documentation
autocomplete:
  enabled: true
  results:
    limit: 15
  exact_match:
    limit: 10
  fuzzy_match:
    threshold: 50
    limit: 10
  trigram_match:
    threshold: 0.4
    limit: 10
  semantic_similarity_match:
    metric: cosine_similarity
    limit: 10
rag:
  enabled: true
  embedding:
    model: text-embedding-ada-002
  retrieval:
    retrieval_method:
      - "top_k_retriever"
      - "reranking"
    top_k_retriever_params:
      top_k: 100
    bm25_retriever_params:
      k: 1.2
      b: 0.75
      top_k: 10
    query_rewriting_retriever_params:
      n_alt_queries: 3
      top_k: 10
    contextual_compression_retriever_params:
      top_k: 4
    rag_fusion_retriever_params:
      n_alt_queries: 3
      rrf_k: 60
      top_k: 3
    reranking_params:
      model: rerank-multilingual-v3.0
      top_k: 5
    routing:
      model: openai
    top_k: 10
    metric: cosine_similarity
  llm:
    model: gpt-4o
    temperature: 0
    max_output_tokens: 2048
    top_p: 0.95
    stream: true
indexing:
  enabled: true
  dev_mode: true
  faq:
    auto_index: !ENV tag:yaml.org,2002:bool ${INDEXING_FAQ_AUTO:false}
  rag:
    auto_index: !ENV tag:yaml.org,2002:bool ${INDEXING_RAG_AUTO:false}
