# Check https://cdc-si.github.io/eak-copilot/ to access config.yaml documentation
autocomplete:
  enabled: true
  results:
    limit: 0
  exact_match:
    limit: 0
  fuzzy_match:
    threshold: 5
    limit: 0
  semantic_similarity_match:
    metric: cosine_similarity
    limit: 0
rag:
  enabled: true
  embedding:
    model: text-embedding-ada-002
  retrieval:
    top_k: 1
    metric: cosine_similarity
  llm:
    model: gpt-4o
    temperature: 0
    max_output_tokens: 512
    top_p: 0.95
    stream: true
indexing:
  enabled: true
  dev_mode: true
  faq:
    auto_index: false
  rag:
    auto_index: false