name: sphinx-build-test
on:
  push:
    branches-ignore: []
  pull_request:
    branches-ignore: []
  schedule:
    - cron: '0 0 * * *'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r doc/requirements.txt
          pip install -r autocomplete/requirements.txt
          pip install -r indexing/requirements.txt
          pip install -r rag/requirements.txt

      - name: Build HTML
        run: |
          cp .env.example .env
          sphinx-build doc _build
